### ISSUE TITLE
Error exporting types directory reference in package.json

### ISSUE THREAD

**Issue by ocarmora** [Refrezsh/strapi-query-builder#2]
I was getting a Typescript error when I was trying to load the library types in my project:

`Could not find a declaration file for module 'strapi-query-builder' ... There are types at ....`

I did fork and realized that, when doing build, the actual directory where the types were located after the build is in `./lib/[esm|cjs]/index.d.ts` instead of `./lib/[esm|cjs]/types/index.d.ts.`

Typescript version: `5.1.6`
Node version: `18.10.0`

**Comment by ocarmora** [comment]
I have just opened a [pull request](https://github.com/Refrezsh/strapi-query-builder/pull/1)

**Comment by Refrezsh** [comment]
The commit seems to be working fine. Thank you very much for your help. 

> I was getting a Typescript error when I was trying to load the library types in my project:
> 
> `Could not find a declaration file for module 'strapi-query-builder' ... There are types at ....`
> 
> I did fork and realized that, when doing build, the actual directory where the types were located after the build is in `./lib/[esm|cjs]/index.d.ts` instead of `./lib/[esm|cjs]/types/index.d.ts.`
> 
> Typescript version: `5.1.6` Node version: `18.10.0`
